baseurl: "https://lockdown.ubnetdef.org/"
languageCode: "en-us"
title: "Lockdown"
theme: "lockdown_v3"
disableHugoGeneratorInject: true

menu:
  main:
    - Name: "about"
      Weight: -100
      URL: "/about"
    - Name: "registration"
      Weight: -90
      URL: "/registration"
    - Name: "rules"
      Weight: -80
      URL: "/rules"
    - Name: "high-school"
      Weight: -70
      URL: "/highschool"
    - Name: "sponsors"
      Weight: -60
      URL: "/sponsors"
